### ISSUE TITLE
Allow modifications of accounts via API

### ISSUE THREAD

**Issue by gakonst** [emschwartz/interledger-rs#117]
Currently the Accounts API only allows inserting new accounts. We should expose an endpoint that allows a node operator to change the `AccountDetails` that correspond to an `Account`, given an `accountId`. This would probably require that the `AccountStore` trait is also adjusted.

**Comment by emschwartz** [comment]
Tracking this feature in https://github.com/emschwartz/interledger-rs/issues/128
