### ISSUE TITLE
Dockerfile  - Redis Unix Socket Update

### ISSUE THREAD

**Issue by Neil-Jubinville** [emschwartz/interledger-rs#122]
Hi,   The default Redis server in the docker build does not seem to point to the right socket location illustrated by the **const REDIS_UNIX_SOCKET = '/tmp/redis.sock'**

I have a fix for the Dockerfile to update the socket field and start the server with an explicit statement of the conf file to use.

Ready to PR / Review.

**Comment by Neil-Jubinville** [comment]
Upon closer inspection of the JS file: run-interledger-node.js   - This should pass the proper value for the socket.     This means the issue is somewhere other than where I was fixing...

It seems a local docker build does not produce the same binaries in the same location as the pulled repository image.    This by looking at /usr/local/bin .

**Comment by emschwartz** [comment]
The images on docker hub are out of date with the latest master. We need to setup an auto-build procedure as part of the CI/CD flow

**Comment by Neil-Jubinville** [comment]
Roger that,  I am now using my own docker build tag.   

I added to my docker file:

`# Update the redis unix socket location
RUN sed -i 's|unixsocket /run/redis/redis.sock|unixsocket /tmp/redis.sock|g' /etc/redis.conf

# Start the Redis Server with specified conf
RUN redis-server /etc/redis-conf &`

This will fix the redis issue.    I have another fix for the run-interledger-node.js file to specifiy the node-config.json   .   I'll need to get sync'd up on how changes get approved and do some PRs I suppose.

**Comment by emschwartz** [comment]
The Docker instructions are being removed in https://github.com/emschwartz/interledger-rs/pull/157
