### ISSUE TITLE
Enabling Config Path - run-interledger-node.js

### ISSUE THREAD

**Issue by Neil-Jubinville** [emschwartz/interledger-rs#127]
I noticed that the path needed to be more explicit for spawning the node command to include the config path.  I changed it to the following on my branch to:

```
    const node = spawn('interledger', [ 'node','--config=/data/node-config.json' ], {
            stdio: 'inherit',
            env
        })
```

This would probably translate to an approved refactor where we can use the CONFIG_PATH.  Maybe something like 

```
    const node = spawn('interledger', [ 'node','--config='+CONFIG_PATH ], {
            stdio: 'inherit',
            env
        })
```

**Comment by emschwartz** [comment]
That file is being removed in https://github.com/emschwartz/interledger-rs/pull/157
