### ISSUE TITLE
Switch to std HashMap

### ISSUE THREAD

**Issue by gakonst** [emschwartz/interledger-rs#130]
Since Rust 1.36 std::collections::HashMap uses hashbrown. 

> In Rust 1.36.0, the HashMap<K, V> implementation has been replaced with the one in the hashbrown crate which is based on the SwissTable design. While the interface is the same, the HashMap<K, V> implementation is now faster on average and has lower memory overhead. Note that unlike the hashbrown crate, the implementation in std still defaults to the SipHash 1-3 hashing algorithm.

However, when implemented in https://github.com/emschwartz/interledger-rs/commit/44fe296edb19aec4c65e1b4c4af9aefb2ecdb8dd, the tests became flaky: https://circleci.com/gh/emschwartz/interledger-rs/623

Close this issue if you replace hashbrown with std::collections without making the test flaky. Maybe has to do with the different hashing algorithm.

**Comment by bstrie** [comment]
Agreed that the different hashing implementation might be behind it, although it also looks like interledger's version of hashbrown is 0.1.8 dating back to January, whereas std is using 0.4.0 from May, so I'll also just try upgrading and see if that shows any flakiness.

**Comment by dora-gt** [comment]
interesting thread.
