### ISSUE TITLE
Same Node Accounts - Failed Transfer

### ISSUE THREAD

**Issue by Neil-Jubinville** [emschwartz/interledger-rs#136]
Imagine a connector with **both alice and bob in it**.  

bob wants to send alice 1500.     

Craft an ILP prepare packet (from your wallet app) **from bob** and send it to the connector.   This prepare packet will state alice as the destination.

The connector in theory should determine that alice is in the same connector and fulfill the request.   Instead I get the following output from the connector trying to process.

```
ilp-node-1_1     | [2019-07-16T14:46:35Z TRACE interledger_http::server] Got incoming ILP over HTTP packet from account: 1
ilp-node-1_1     | [2019-07-16T14:46:35Z TRACE interledger_router::router] Found direct route for address: "local.alice". Account: 0
ilp-node-1_1     | [2019-07-16T14:46:35Z TRACE interledger_service_util::exchange_rates_service] Converted incoming amount of: 1500 ABC (scale 9) from account 1 to outgoing amount of: 1500 ABC (scale 9) for account 0
ilp-node-1_1     | [2019-07-16T14:46:35Z TRACE interledger_store_redis::store] Processed prepare with incoming amount: 1500. Account 1 has balance (including prepaid amount): -1500
ilp-node-1_1     | [2019-07-16T14:46:35Z TRACE interledger_btp::service] No open connection for account: 0, forwarding request to the next service
ilp-node-1_1     | [2019-07-16T14:46:35Z TRACE interledger_btp::service] No open connection for account: 0, forwarding request to the next service
ilp-node-1_1     | [2019-07-16T14:46:35Z ERROR interledger::node] No route found for outgoing account 0
ilp-node-1_1     | [2019-07-16T14:46:35Z TRACE interledger::node] Rejecting request to account 0, prepare packet: Prepare { destination: Address("local.alice"), amount: 1500, expires_at: "2019-07-16T14:51:29.214+00:00", execution_condition: "0000000000000000000000000000000000000000000000000000000000000000", data_length: 4 }
ilp-node-1_1     | [2019-07-16T14:46:35Z TRACE interledger_store_redis::store] Processed reject for incoming amount: 1500. Account 1 has balance (including prepaid amount):
```

I made sure bob has min balance of -10,000 and even bumped up the prepaid to 77,000 to see if those made a difference.

- why is local processing context looking for open btp connections as the route?    
- should we create a btp loopback?
- do we need to add logic to check for local account transfers?

**Comment by emschwartz** [comment]
Good question. Right now there is no way to send a payment to an account without the account-holder actively accepting it. The connector is looking to forward the packet to the account holder for them to fulfill it.

If you want to send money to an account on an interledger.rs node, you can send an SPSP payment to `/spsp/<their account id>`, in which case the node will act as the receiver and fulfill the packets on their behalf.

**Comment by Neil-Jubinville** [comment]
Ok thank-you,  certainly I am just exploring the lower level of the protocol as you can see :)   My apologies for every question resulting in pointing me back to SPSP. :)

**Comment by emschwartz** [comment]
No problem at all. We should make these types of things clearer in the docs
