### ISSUE TITLE
SPSP API Request - Get Secret -  ID Not Found

### ISSUE THREAD

**Issue by Neil-Jubinville** [emschwartz/interledger-rs#137]
Hi,   I am trying to hit the SPSP endpoint where it returns a secret but I am getting ID not found error.    I am curious if I am providing the proper URL.

I tried the following requests:

-  http://localhost:7770/spsp/g.buddy
-  http://localhost:7770/spsp/buddy
-  http://localhost:7770/spsp/$g.buddy
-  http://localhost:7770/spsp/$buddy

They all yield:
```
[2019-07-16T19:06:38Z ERROR interledger_api::routes::spsp] Invalid id: g.buddy
[2019-07-16T19:06:49Z ERROR interledger_api::routes::spsp] Invalid id: $g.buddy
[2019-07-16T19:06:56Z ERROR interledger_api::routes::spsp] Invalid id: buddy
[2019-07-16T19:09:19Z ERROR interledger_api::routes::spsp] Invalid id: g.buddy
[2019-07-16T19:15:35Z ERROR interledger_api::routes::spsp] Invalid id: $buddy
```

The rust code below is from spsp.rs api showing where the error message is from,  and the creation of that service as a whole in the node.rs indicates it is the same underlying store reference used.     So I don't it is using a different or empty store.

```

  #[get("/spsp/:id")]
        fn get_spsp(&self, id: String) -> impl Future<Item = Response<Body>, Error = Response<()>> {
            let server_secret = self.server_secret.clone();
            let store = self.store.clone();

            
            let id: Result<A::AccountId, ()> = A::AccountId::from_str(&id).map_err(|_| error!("Invalid id: {}", id));
            result(id)
                .map_err(|_| Response::builder().status(400).body(()).unwrap())
                .and_then(move |id| store.get_accounts(vec![id])
                .map_err(move |_| {
                    error!("Account not found: {}", id);
                    Response::builder().status(404).body(()).unwrap()
                }))
                .and_then(move |accounts| {
                    // TODO return the response without instantiating an SpspResponder (use a simple fn)
                    Ok(SpspResponder::new(accounts[0].client_address().clone(), server_secret)
                        .generate_http_response())
                    })
        }
```

**Comment by Neil-Jubinville** [comment]
OK I just got it working with :   http://localhost:7770/spsp/0

**Comment by emschwartz** [comment]
Right now it's designed to use the numeric account ID.

One more clarification: the Payment Pointer for that account would be something that looks like `$domain.example/spsp/0` (or you could have a URL redirect so it might look nicer, along the lines of `$alice.domain.example`). The only reason we can't use that when testing locally is that Payment Pointers always resolve to an HTTPS endpoint but we're only running plain HTTP locally. For this reason, SPSP clients also allow passing in the full SPSP URL, like you're doing in this case, instead of the slightly more user-friendly Payment Pointer.

**Comment by emschwartz** [comment]
We may want to add usernames and either replace the numeric account lookup with the full username or support both. I think this would make it easier to automatically redirect a payment pointer like `$alice.domain.example` to `https://domain.example/spsp/alice`.

**Comment by Neil-Jubinville** [comment]
Awesome, that would be useful and intuitive. 👍   especially when dynamically created!

**Comment by emschwartz** [comment]
I opened https://github.com/emschwartz/interledger-rs/issues/137 to track the status of that feature
