### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by ekrenzke** [emschwartz/interledger-rs#14]
I am currently going through the existing codebase and trying to add documentation wherever possible, using [this](https://github.com/interledger/rfcs) as my reference.

- [x] ILP Packet
- [x] BTP Packet
- [ ] STREAM Packet
- [ ] Errors

Right now, I am currently focused on updating the lower-level primitives that will not be exposed to the bindings. If there is a specific area that you would like to see more documentation for, please let me know or contribute by submitting a PR.

**Comment by emschwartz** [comment]
This is in progress
