### ISSUE TITLE
Consider removing `ilp_address` from SettlementEngineDetails

### ISSUE THREAD

**Issue by sappenin** [emschwartz/interledger-rs#144]
Per convo in the Slack channel, it seems like the ILP address of a SettlementEngineDetails should always just be `peer.settle`. Assuming there's a `SettlementEngineDetails` per account, then this address should not be necessary. Packets that come in from a peer having a destination_address of `peer.settle` will always just be routed to the `handle_request` in `SettlementMessageService`.

I think this means we would also remove [this check](https://github.com/emschwartz/interledger-rs/blob/master/crates/interledger-settlement/src/message_service.rs#L48) as well.

**Comment by gakonst** [comment]
Agreed, including this in my current PR.
