### ISSUE TITLE
Add account usernames 

### ISSUE THREAD

**Issue by emschwartz** [emschwartz/interledger-rs#147]
Right now, accounts are identified by a numeric ID and use a bearer token only for authentication. It would be more developer-friendly to give each account a username, use that as part of the authentication, and use the username instead of a number in the HTTP path for queries like `/spsp/:account_id`.

This originally came up in https://github.com/emschwartz/interledger-rs/issues/137

**Comment by emschwartz** [comment]
One question for this: how should the client send their username to the API? Should they use HTTP Basic auth with username and the API key as the password? Or should they set another header?

**Comment by sappenin** [comment]
Another alternative to consider (besides Basic auth or a separate header) is to maintain the Bearer-token style but with some encoded data in the token.

I know how much you like JWTs.....

:)

...but you could include the "username" as the `sub` (subject) claim in a JWT, and then issue that as a Bearer token. As an example:

```
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlbXNjaHdhcnR6In0.02RlzGVeLG1ijbI56PO7gS0VcUmI-n4Vh__ReAgicf4
```

(plug the b64 portion into [https://jwt.io](https://jwt.io) to see the decoded values)

**Comment by emschwartz** [comment]
Folding this issue into https://github.com/emschwartz/interledger-rs/issues/186
