### ISSUE TITLE
Add a readme to every crate in the workspace

### ISSUE THREAD

**Issue by bstrie** [emschwartz/interledger-rs#151]
To ease people into the codebase it would be nice for each crate to document the general role it plays (does not need to be comprehensive). Put a readme at the root of each crate (same level as the Cargo.toml) in order to display optimally on Github.

- [x] interledger-api
- [x] interledger-btp
- [x] interledger-ccp
- [x] interledger-http
- [x] interledger-ildcp
- [x] interledger-packet
- [x] interledger-router
- [x] interledger-service-util
- [x] interledger-service
- [ ] interledger-settlement
- [ ] interledger-settlement-engines
- [x] interledger-spsp
- [x] interledger-store-memory
- [x] interledger-store-redis
- [x] interledger-stream
- [x] interledger

**Comment by emschwartz** [comment]
Similar to https://github.com/emschwartz/interledger-rs/issues/88

In any case, I'm very supportive of adding this

**Comment by emschwartz** [comment]
@bstrie is this done or is there still more to do on this?

**Comment by bstrie** [comment]
I've updated the issue, the two settlement crates could still use readmes with short descriptions of what their purpose is.
