### ISSUE TITLE
Should the IlpAddress property on an Account be optional (or removed)?

### ISSUE THREAD

**Issue by sappenin** [emschwartz/interledger-rs#161]
[Accounts](https://github.com/emschwartz/interledger-rs/blob/master/crates/interledger-api/src/lib.rs#L52) in this implementation currently require an ILP address in order to be created.

From the perspective of a Connector that has no receiver capability (i.e., no SPSP server, but instead only routes packets from an incoming link through to an outgoing link), then having an ILP address on an account doesn't seem to add any value.

For example, imagine two Connectors, `alice` and `bob` with a single link between them, both routing packets onward past themselves. For Alice, alice's routing table will indicate all of the destination ILP addresses that are eligible to be forwarded on her link with `bob`. And vice-versa for Bob. In other words, Connectors routing packets only ever consult their routing table (not some property on an account). Between CCP and static routes, the Connectors have everything they need to route packets.

Now, this gets a bit more complicated if a Connector allows an account to be addressable on the Interledger and thus to fulfill packets (i.e., the Connector is _also_ a per-account receiver, such as via SPSP). 

In this world, I think it _would_ be useful to allow a particular account to specify its own ILP address (within reason). This address property would trump any automatic or domain-level address given to receiver accounts on a Receiver system.

In Rust, the implementation provides both functionalities (ILP router _and_ ILP receiver) in a single package/process, so the `Account` primitive logically includes an `ILP Address` property.

At the least, I think this property should be optional. However, might it be clearer to consider two types of Accounts in Rust -- a "peering" Account (no ILP address) and a Receiver account?

As an example, in the Java implementation, the Connector has no "receiver" functionality. Receiver functionality will (for now at least) be a separate runtime, with a peer-link between the Connector and the receiver. Because of this, I think the distinction between the needs of the two types of accounts is more obvious because the two systems are _always_ separate, and a pure Connector that isn't fulfilling packets doesn't need this property in its account primitive.

**Comment by Neil-Jubinville** [comment]
I think it works to be optional if there is a need for an ILP routing only mechanism, like say in some deeper backend private infrastructure where one moves money around for your own private corporate purposes.   I can see this " no fee" zone.  

However in the realm of public routing a 'house' account would need to exist to receive transmission fees from forwarding ILP.

**Comment by emschwartz** [comment]
Good call! :+1: on removing the `ilp_address` or making it optional.

These are the ways the ILP address is currently used (all references can be found [here](https://github.com/emschwartz/interledger-rs/search?p=2&q=client_address&unscoped_q=client_address)):
1. Handling ILDCP requests
2. Creating the `destination_account` for SPSP/STREAM
3. Populating the routing table

1 and 2 can be replaced by appending the [username](https://github.com/emschwartz/interledger-rs/issues/147) to the node's ILP address.

3 is unnecessary because you can configure static routes that force specific prefixes to go to the correct account.

**Comment by emschwartz** [comment]
Folding this issue into https://github.com/emschwartz/interledger-rs/issues/186
