### ISSUE TITLE
Use yaml file for CLI definition

### ISSUE THREAD

**Issue by emschwartz** [emschwartz/interledger-rs#169]
`clap` supports using YAML files to define the CLI (see example [here](https://github.com/clap-rs/clap/blob/master/examples/17_yaml.yml)).

By defining the CLI in Rust, we need to turn off Clippy's warnings about cognitive complexity for the statement that sets it up (see [here](https://github.com/emschwartz/interledger-rs/blob/master/crates/interledger/src/main.rs#L13)).

I think it might be simpler to just move the definition to a separate `.yml` file. Thoughts? @gakonst @bstrie

**Comment by bstrie** [comment]
I haven't tried it yet, but I was hoping that splitting out the binaries into separate crates would allow us to simplify that function such that the annotation could be removed. That said, I'm generally in favor of using the least powerful language that will accomplish any given task, so I'm mildly in favor... although YAML is a hairy format and I have no experience with how reliable its Rust parsers are. If it was something simpler like TOML I'd say yes much more readily.

**Comment by bstrie** [comment]
My other concern is that this would probably involve adding another set of dependencies, which I'm generally looking to reduce at present.

**Comment by tarcieri** [comment]
Have you looked at using `structopt` to construct each of the (sub)commands as structs, and their options/args as members thereof? IMO it's a lot cleaner, especially if you factor each of those structs along with the relevant functionality they invoke into their own module (this is the pattern Abscissa enforces, FWIW, albeit with `gumdrop_derive`)

**Comment by bstrie** [comment]
I'm all for exploring alternatives for argument parsing, although I'd hold off until I land the aforementioned binary split.

**Comment by emschwartz** [comment]
@tarcieri I have not, but those look like better options. :+1: for switching
