### ISSUE TITLE
Add identifier for each settlement engine instance

### ISSUE THREAD

**Issue by kincaidoneil** [emschwartz/interledger-rs#178]
If a settlement engine instance is ever migrated to a different port or IP address, every account linked to that settlement engine must have the URL associated with it updated. 

If there was a separate mapping of settlement engine identifiers to settlement engine URLs, each account could be linked to the immutable settlement engine identifier, and the URL would only have to be updated in a single place.

**Comment by emschwartz** [comment]
I think we're going to keep the URLs configured on each account for now. If we run into situations where we need to move the SE and this becomes a huge pain, we can make this change later
