### ISSUE TITLE
Add examples for multi-hop and cross-currency payments

### ISSUE THREAD

**Issue by emschwartz** [emschwartz/interledger-rs#182]
- [ ] Three node
- [ ] Three node with settlement using 2 settlement engines

**Comment by gakonst** [comment]
I'll be taking this starting tomorrow, since I already got XRP and ETH payments working separately.

**Comment by gakonst** [comment]
An XRP - ETH + settlements example is done in #184 #187 and #192

**Comment by emschwartz** [comment]
This is done
