### ISSUE TITLE
Question: Should settlement trigger _at_ the threshold, or _above_ the threshold?

### ISSUE THREAD

**Issue by sappenin** [emschwartz/interledger-rs#189]
This is sort of a nit-picky question/issue, but while I was testing the Java Connector's Settlement Engine implementation, I wrote an integration test that was expecting to see settlement get triggered once a balance hit `10` units. As such, I set my `settlement_threshold` for each account to `10`, issued some payments to take the balance to 10, but was surprised that settlement was never triggered.

After investigating a bit, it turns out that the Java LUA script for Fulfillment (which mirrors the Rust LUA script, FWIW) doesn't trigger settlement until the `balance` _exceeds_ the threshold (see [here](https://github.com/emschwartz/interledger-rs/blob/master/crates/interledger-store-redis/src/store.rs#L90) for the RUST implementation's script).

This was counter-intuitive to me, so I adjusted the Java project's Lua script to instead do this (basically use an `>=` for the balance/settle_threshold): 

```
if (settle_threshold and settle_to) and (balance >= tonumber(settle_threshold)) and (tonumber(settle_threshold) >= tonumber(settle_to)) then
```

I _think_ (?) Rust should follow suit (though if you guys disagree I'll probably revert the Java implementation so both impl's do the same thing).

I'm pretty sure adding that last `>=` (i.e., for `settle_threshold` and `settle_to`) has no effect. But adding a `>=` for the balance/settle_threshold does make it so I can say, "My Threshold is `10` and when the balance reaches that threshold I expect it to trigger a settlement."

**Comment by emschwartz** [comment]
Sounds right to me

**Comment by gakonst** [comment]
Agreed, maybe recommend the variable from `settle_threshold` to something more fitting? A threshold means you can tolerate up to that number, and the action is taken only when you exceed it.

**Comment by sappenin** [comment]
> A threshold means you can tolerate up to that number

That's what I thought at first, but after investigating the dictionary definitions, I think it's more accurate to conceive of a threshold as just a point (like the threshold of a door or a numerical amount). It's a concept that can stand on its own, and it's an orthogonal concept as to whether you can "meet" or "exceed" a threshold.

In other words, whether you want to "tolerate" something equal-to, above, or below a threshold is not actually part of the definition of a threshold (though it's easy to think otherwise). 

For evidence, see the examples [here](https://www.google.com/search?q=Dictionary#dobs=threshold), specifically the "pain threshold" where the example says, "a limit below which a stimulus causes no reaction." Also, see [here](https://www.dictionary.com/browse/threshold).

> maybe recommend the variable from settle_threshold to something more fitting

I kind of like the word "threshold" (despite my own initial confusion) because it seems to capture what we're doing. 

**More importantly, the motivation for this issue is instead whether we want to trigger settlement _at_ the threshold, or _above_ it.**

My opinion is that we trigger settlement _at_ the threshold, i.e., when the balance _reaches_ the threshold.
