### ISSUE TITLE
Output of examples/simple/run-all.sh does not redirect to file

### ISSUE THREAD

**Issue by KevinWMatthews** [emschwartz/interledger-rs#201]
This may be deprecated by #180 and #190, but I'll add it to help clarify why/how `run-all.sh` is logging to the console #202.

On my PC it looks like `sh` does not redirect output to a file.

This has an effect on the script `examples/simple/run-all.sh`, specifically:

```bash
sh start-services.sh
```

which executes:

```bash
redis-server &> logs/redis.log &
cargo run --package interledger -- node --config ./node-a/config.yml &> logs/node-a.log &
cargo run --package interledger -- node --config ./node-b/config.yml &> logs/node-b.log &
```

The services do run in the background but they do not redirect properly. There is a tangle of output on the console and empty log files.

On this machine I can solve the problem by changing `run-all.sh` to use `bash`:

```bash
bash kill-services.sh
bash start-services.sh
bash create-accounts.sh
# etc
```

I'm running an older (but supported) Linux distro on this box - Linux Mint 18:

```
$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="18 (Sarah)"

$ cat /etc/debian_version 
stretch/sid
```

Do you see something similar? Is this by design? I can post the console output if it's helpful.

**Comment by dora-gt** [comment]
Hello Kevin,

I'm not sure what shell you use but it might be concerned with the implementation.
We are currently working on the improvement of examples and in the next version, we will explicitly use `bash` for our example.

So it would be solved soon.

#190

**Comment by KevinWMatthews** [comment]
Looks like I'm using `dash` be default; `/bin/sh` is symlinked to `dash`.

I see that `run-md.sh` [explicitly uses `bash`](https://github.com/dora-gt/interledger-rs/blob/5b5d984390b470aa08fe770df4fc6c2e52a0a544/scripts/run-md.sh#L38). That fixes this for me.
