### ISSUE TITLE
Using `ilp-ping` to ping node that `moneyd` is connected to fails

### ISSUE THREAD

**Issue by wliu** [emschwartz/interledger-rs#210]
I'm able to connect to a rust node via `moneyd` + `btp` successfully. However, when trying to use `ilp-ping`, I get the following error:

```vagrant@ubuntu-bionic:~$ ilp-ping test.xpring-dev.rs1
ILP-PING test.xpring-dev.rs1
Error sending ping. code=T01 message= triggeredBy=
Error sending ping. code=T01 message= triggeredBy=
Error sending ping. code=T01 message= triggeredBy=
Error sending ping. code=T01 message= triggeredBy=
```
In the above example , `moneyd` is connected to that same node `test.xpring-dev.rs1`.

**Comment by emschwartz** [comment]
@dora-gt could you test [`ilp-ping`](https://github.com/martinlowinski/ilp-ping) against the rust implementation of the Echo protocol?

**Comment by dora-gt** [comment]
I'm sorry that my part causes an error. I'll look into.
