### ISSUE TITLE
SPSP / STREAM Server Lambda Function

### ISSUE THREAD

**Issue by emschwartz** [emschwartz/interledger-rs#25]
It would be cool to make a deconstructed SPSP / STREAM receiver designed for AWS Lambda (using the new [Rust runtime](https://github.com/awslabs/aws-lambda-rust-runtime)).

To build this we would need:
- [x] An [HTTP-based ledger plugin protocol](https://github.com/emschwartz/ilp-rs/issues/26) (instead of BTP over WebSockets)
- [ ] A standalone SPSP Server Lambda function that handles just the HTTPS requests
- [x] A STREAM receiver function that processes a single incoming ILP Prepare with a STREAM packet attached and returns the fulfillment + response packet **(implemented in https://github.com/emschwartz/interledger-rs/pull/29)**

Other notes:
- The STREAM receiver should probably write details of the money received into a database like DynamoDB (probably using [rusoto](https://github.com/rusoto/rusoto)) 
- The server secret used to generate the STREAM shared secret would probably be passed in via environment variable

**Comment by emschwartz** [comment]
Actually it would be worth looking into whether the performance is better with each lambda function handling a single incoming ILP packet or having the receiver be longer-lived. The expected use case is that a lot of packets will come in for the same receiver within a relatively short period of time. I wonder whether the overhead of starting up the lambda function would outweigh the performance benefits, or whether the flexibility and easy scaling would make it worth it.

**Comment by ekrenzke** [comment]
> Actually it would be worth looking into whether the performance is better with each lambda function handling a single incoming ILP packet or having the receiver be longer-lived.

I believe there are some work-arounds to prevent cold starts by calling all lambda functions periodically from a separate scheduled lambda function. This mitigates the response time from a ~5 second cold start to something more tolerable.

**Comment by d1no007** [comment]
This is really interesting. Yeah in regards to cold starts you can warm up the lambda function beforehand with something that hits it with an http/https request. Although I’m not sure how lambda functions deal with concurrent requests. If you warm up one, would the others cold start?

**Comment by emschwartz** [comment]
Thinking about it more, the cold start shouldn't be a problem because the same lambda function can handle incoming packets for different STREAM connections. It wouldn't need to wake them up and put them to sleep for every packet.

**Comment by emschwartz** [comment]
I don't think a lambda function is a good idea after all. However, I did switch the stream receiver to be stateless and the whole architecture is now oriented around a simpler request/response pattern
