### ISSUE TITLE
HTTP-based ledger plugin

### ISSUE THREAD

**Issue by emschwartz** [emschwartz/interledger-rs#26]
There are two ways to design this protocol. Either:
1. One side is the HTTP client and the other is the HTTP server
2. Both sides are HTTP clients and servers

The problem with 1 is how to handle incoming Prepare packets on the client side. It could poll the server, but (long) polling is kind of clunky. We would also need IDs to correlate request and response packets. If we wanted to have multiple instances of the plugin running concurrently, they would all need to be feeding the packets they get into the same database, because we couldn't guarantee that the same instance gets the response to its Prepare. Finally, WebSockets were specifically designed for bidirectional communication between a client and server, so BTP probably serves this use case better than a purely HTTP-based protocol would.

Option 2 is much easier. To send outgoing Prepare packets, the sender would `POST /ilp` with the packet in the HTTP request body and the HTTP response would contain the Fulfill or Reject packet (if we want idempotency, we _could_ make it `PUT /ilp/:uuid`). This would work the same way in both directions. Every packet would carry the auth details (using the normal HTTP `Authorization` header), and we could optionally upgrade to HTTP/2 to speed the whole thing up. If there are other "sub protocols" like payment channel claims now sent over BTP, those could just use a different URL (`POST /xrp-paychan` for example).

**Comment by tarcieri** [comment]
I've been making progress on my minimalist HTTP crate `gaunt`:

https://github.com/iqlusioninc/crates/tree/master/gaunt

It's presently client-only, although I intend to add server support. The current public API is pretty far from what I'd eventually like to have though, and more like an internal API I haven't wrapped up yet.

It presently powers the HTTP backend of [yubihsm-rs](https://github.com/tendermint/yubihsm-rs).

**Comment by emschwartz** [comment]
Done
