### ISSUE TITLE
Check max data size and ILP address length

### ISSUE THREAD

**Issue by emschwartz** [emschwartz/interledger-rs#37]
The packet parsing module should not accept packets whose data or address lengths exceed the max values

**Comment by dora-gt** [comment]
I think both 2 are needed in the server.

1. Checking the length of the entire data the server is going to receive, to prevent some malicious attackers from uploading a huge amount of data. Though I haven't dug into whether this is addressed or not.
1. Checking each field (address and data), whether the size is correct.

What do you think?

**Comment by dora-gt** [comment]
memo:
- [InterledgerProtocol.asn](https://github.com/interledger/rfcs/blob/master/asn1/InterledgerProtocol.asn)
- [InterledgerTypes.asn](https://github.com/interledger/rfcs/blob/master/asn1/InterledgerTypes.asn)

**Comment by emschwartz** [comment]
> Checking the length of the entire data the server is going to receive, to prevent some malicious attackers from uploading a huge amount of data. Though I haven't dug into whether this is addressed or not.

Great point. You're right that both the HTTP and BTP servers should limit the incoming data sizes.

> Checking each field (address and data), whether the size is correct

Yup, that should be in the ilp-packet crate

**Comment by sentientwaffle** [comment]
1. https://github.com/coilhq/interledger-relay/blob/master/crates/interledger-relay/src/combinators/limit_stream.rs might be useful
2. already implemented in https://github.com/coilhq/interledger-rs/tree/dj-connector-relay2 -- I'll get around to polishing it up and creating a PR soon.

**Comment by dora-gt** [comment]
Oh, so I don't need to fix 2.

About `1`, doesn't `hyper` have such a function?
I'll look into it.

**Comment by dora-gt** [comment]
I got an answer from hyper gitter,

```
Michal 'vorner' Vaner @vorner 02:40
I don't think it has that directly. But you get the body as a stream, so you can drop the stream and return an error after you've read enough.
```

Ultimately using `limit_stream` might be the right option🤔

**Comment by dora-gt** [comment]
@sentientwaffle Could you tag the version so that the source which we use can be fixed.

**Comment by gakonst** [comment]
Can we close this? https://github.com/emschwartz/interledger-rs/pull/62 is merged
