### ISSUE TITLE
Add echo protocol handler

### ISSUE THREAD

**Issue by emschwartz** [emschwartz/interledger-rs#60]
Implement the [Echo](https://github.com/interledgerjs/ilp-connector/blob/master/src/controllers/echo.ts) protocol as an `IncomingService`. It should inspect the request to determine whether the packet corresponds to the Echo protocol and, if so, swap out the Prepare packet for one addressed to the destination address from the original packet data. As long as this service is inserted before the Router, nothing else should need to change to handle this protocol. The fulfillment will be returned as normal to the previous hop.

**Comment by dora-gt** [comment]
I'm thinking of the basic policy to tackle this.
What do you think?

### Basic policy
- Make a new crate (`interledger-echo`)
  - It seemed that services had its own crate like `interledger-ildcp`
- Define the service in `server.rs` file
  - It seemed that:
    - `server.rs` processes incoming data
    - `client.rs` connects to the other nodes and process its connections
- Insert the service into each connection (probably in `cli.rs`):
  1. BTP connections
  1. HTTP connections

Also we might need `client.rs` to test or implement the echo function🤔

**Comment by emschwartz** [comment]
I would actually put it in `interledger-service-util`. @sentientwaffle and I were discussing getting rid of the ILDCP crate and merging it with others.

That service just needs to be added to the chain of incoming handlers in the ILP Node bundle: https://github.com/emschwartz/interledger-rs/blob/c8baf4d8db35d5a4dc3468a0f5ebb11adf9bc95a/crates/interledger/src/node.rs#L183

I think it's fine to just have unit tests for this one. We'll need proper integration tests with the other implementations but that's a bigger project

**Comment by dora-gt** [comment]
Ok, thank you!

**Comment by dora-gt** [comment]
I’m going to implement `echo` server as this brief spec:
https://github.com/dora-gt/interledger-rs/wiki/Fix-%2360#brief-spec
If you find something wrong or you have any opinions, please tell me.

**Comment by emschwartz** [comment]
Resolved by https://github.com/emschwartz/interledger-rs/pull/71

We should open a separate ticket for adding the [ping / unidirectional echo protocol](https://github.com/interledger/rfcs/pull/516) when that is finalized.
