### ISSUE TITLE
Create an IlpAddress type

### ISSUE THREAD

**Issue by emschwartz** [emschwartz/interledger-rs#69]
This type should:
- [x] Wrap a [`Bytes`](https://github.com/carllerche/bytes)
- [x] Check that the address conforms to the [spec](https://interledger.org/rfcs/0015-ilp-addresses/)
- [x] Implement `Debug`, `Display`, `FromStr`
- [ ] Implement `Deref` for the targets `&str` and `&[u8]`
- [x] Implement serde's `Serialize`, `Deserialize`

This will let us efficiently use the addresses and avoid copying them but also enable printing them without constantly re-parsing the bytes as utf8.

Credit to @sentientwaffle for this idea.

**Comment by emschwartz** [comment]
Actually it looks like @sentientwaffle implemented a lot of this in his fork [here](https://github.com/emschwartz/interledger-rs/blob/dj-connector-relay2/crates/interledger-packet/src/address.rs). I don't think that hits all of the pieces of this issue but it would probably be worth using that as a starting point.

**Comment by emschwartz** [comment]
Continuing the discussion from https://github.com/emschwartz/interledger-rs/pull/75#issuecomment-498396636 and https://github.com/emschwartz/interledger-rs/pull/75#issuecomment-498422561, should we have a single `Address` type or `Address` (owned) and `Addr` (borrowed) types?

The main advantage we see thus far of having a single `Address` type is the simplicity and the main disadvantage seems to be the performance of internally calling `Arc::clone` within the wrapped `Bytes`.

@sentientwaffle do you know if using an `&Address` in places like the `PrepareBuilder` and `RejectBuilder` that have lifetimes specified would avoid that atomic operation?

**Comment by emschwartz** [comment]
From @gakonst in https://github.com/emschwartz/interledger-rs/pull/75#issuecomment-498428403:
> My understanding is that the goal is to replace the destination and triggered_by fields with Address and Option<Address> (since triggered_by can be empty) fields.
> We should avoid using the raw Bytes and go for the Address type in as many places as possible to ensure that the correct format is enforced

I agree, though I think the question is whether calling those methods triggers an `Arc::clone` operation internally to pass a clone of the internal `Bytes` to the new `Address` instance. Those methods are called a lot throughout the code so we'd want the performance overhead to be as minimal as possible (I'm not sure what order of magnitude of performance hit we're talking about here though).

**Comment by gakonst** [comment]
Note that `triggered_by` takes `Option<&'a Address>` as of https://github.com/emschwartz/interledger-rs/pull/77/commits/54df2717c34a1bb3a04d348e6a3c61edff3dcfa8 (this is the follow-up PR), so maybe the ovehead won't be as large.

**Comment by gakonst** [comment]
Also, it'd be nice to make functions accept `AsRef<Address>` or `TryInto<Address>` instead of `Address` such that the API is cleaner and requires less type conversions from the consumer side. It would however require making all these functions return a result, for the cases that they were called with invalid addresses, which I think is fine.
