### ISSUE TITLE
Create Route type

### ISSUE THREAD

**Issue by gakonst** [emschwartz/interledger-rs#79]
Currently the routes inside ilp-router are `Bytes`. We were earlier talkign with @emschwartz about replacing them with the new Address type. However, this doesn't make much sense, as we want [prefix matching](https://github.com/emschwartz/interledger-rs/blob/master/crates/interledger-router/src/router.rs#L286). Some routes might be even [empty](https://github.com/emschwartz/interledger-rs/blob/master/crates/interledger-router/src/router.rs#L255).

We could create a new `Route` type to be used as the key of the [hashmap](https://github.com/emschwartz/interledger-rs/blob/master/crates/interledger-router/src/lib.rs#L33) alongside helper methods for it. 

Is this worth putting effort into, or should we stick with the Bytes type here? Note that after merging #75, variables such as [`destination`](https://github.com/emschwartz/interledger-rs/blob/master/crates/interledger-router/src/router.rs#L39) will be `Address`, and as such we'll have to convert them to `Bytes` for the `starts_with` etc. comparisons.

**Comment by emschwartz** [comment]
Good questions. The 3 options we have are:
1. Stick with `Bytes` in the Router
2. Add a `Route` type or an Enum that wraps `Address` or `Bytes` (for the prefixes that aren't valid addresses)
3. Allow empty strings and bare prefixes in the `Address` type

The first option seems fine, though it would go in the face of some of the reason we are adding the `Address` type in the first place. The `Address` can be printed for debugging purposes without re-parsing the bytes each time. Also, we want the details from the routing table to be easily (de)serializable for the [API](https://github.com/emschwartz/interledger-rs/blob/7eb202653f646e6165b5cb6393189faf2d63de9f/crates/interledger-api/src/lib.rs#L272-L309).

The second option also could work but adds some developer overhead, as described above. Also, if this `Route` type needs to be exposed to the API, we would have to duplicate a lot of the (de)serialization code from the `Address` type.

For the third option, raw prefixes and empty strings definitely aren't considered valid ILP addresses according to the spec. However, we can look at this from the perspective of the practical question "is there anywhere that having an empty `Address` would create an error or failure and require an Option to be returned where that wouldn't have been the case if we disallowed such addresses?" I think the answer to this is no. `Address`es are mostly used for prefix matching, printing, and parsing from ILP packets. In each of these cases, I don't think allowing "partial" addresses would cause any real problems.

Unless anyone can point out a specific place where allowing prefixes or empty strings as `Address`es would cause problems, I would opt for the 3rd option.

**Comment by tarcieri** [comment]
Not sure how relevant this is to the ILP use case, but in traditional IP routing this is where you'd typically use a radix tree:

https://www.juniper.net/documentation/en_US/junos/topics/usage-guidelines/policy-configuring-route-lists-for-use-in-routing-policy-match-conditions.html

**Comment by sentientwaffle** [comment]
@emschwartz I think (1) is the best option. (2) seems unnecessarily complicated.

re:(3):  The purpose of the `Address` type is mainly to validate addresses, so it seems weird to me that it would be allowed to contain an invalid address.

**Comment by emschwartz** [comment]
I think we're sticking with Bytes for now so I'm going to close this issue
