### ISSUE TITLE
Rename generic parameters for consistency

### ISSUE THREAD

**Issue by gakonst** [emschwartz/interledger-rs#84]
(all my comments are based on commit `500577`

Since the codebase is heavy on generics, I suggest we rename (and even add some guidelines to a CONTRIBUTING.md) file for the following:

`I` for `IncomingService`
`O` for `OutgoingService`
`IO` in the struct declaration when it can be either (e.g. check the ValidatorService)
`S` for `AccountStore` and the store variants: 
`A` for `Account`
`F` for functions

also try to be consistent with `Outgoing` and `IncomingService` definitions

let's target for: <address><store><next>

```rust
pub struct Service<S,I,A> {
   ilp_address: Address,
   store: S,
   next: I // or O,
   account_type: PhantomData<A> // optional
}
```

**Comment by emschwartz** [comment]
Sounds great! It's bothered me while writing them that they haven't been perfectly consistent but I should have gone through and done this already. Good suggestion.
