### ISSUE TITLE
Investigate static lifetimes 

### ISSUE THREAD

**Issue by gakonst** [emschwartz/interledger-rs#89]
When implementing a service sometimes we are forced to use `'static` lifetimes:

https://github.com/emschwartz/interledger-rs/blob/es-settlement/crates/interledger-service-util/src/rate_limit.rs#L52-L70
https://github.com/emschwartz/interledger-rs/blob/es-settlement/crates/interledger-service-util/src/balances.rs#L63-L66
https://github.com/emschwartz/interledger-rs/blob/master/crates/interledger-btp/src/service.rs#L47
...etc

Is there a better way around this? It seems to be that it might be required, due to how tokio works (reddit comment for "reference" https://www.reddit.com/r/rust/comments/8rhmj8/how_does_static_lifetime_work/e0rr3y1/)

**Comment by emschwartz** [comment]
Yeah, this is just what you need to do when using Tokio now. I think switching to Futures 0.3 + async/await may remove the need to use `'static`

**Comment by gakonst** [comment]
We can remove the comments from the code hinting at static not being needed.
